# These flags were pulled from
# https://github.com/KennethHarmon/card-project
# I have made some changes and additions
redflags = [
    'Has a dozen kids from a dozen partners',
    'Is 40 years older than they are in their profile picture',
    'Uses way way way too much tongue',
    'Steals something from every store they enter',
    'Looks and smells just like your dad',
    'Says "like", like all the time',
    'Is wanted in every state except Florida',
    'Amateur vigilante',
    "Swears they're eighteen",
    'Only speaks in hashtags',
    'Demands to pop all of your zits for you',
    'Is your clone',
    "Literally won't talk to you if you're part of the wrong Hogwarts house",
    'Only speaks in horrible puns',
    'Teleports to the North Pole every time they say the word "love"',
    'Only speaks in Disney song lyrics',
    'Calls you a "4" to your face',
    'Has the names of all of their exes tattooed on their face',
    'Repeats your jokes but louder',
    'Is banned by the Make-A-Wish foundation',
    'Is a merperson',
    'Conveniently forgets wallet every date night, always has I.D. though',
    'Is always watching porn',
    'Worst-smelling person in the world',
    'Laughs incessantly during sex',
    'Has the face of a pug',
    'Tries to pay for everything with farm animals',
    'Sees the ghost of everyone who has ever died',
    'Only speaks in yelling',
    'Only speaks in yodelling',
    'Is actually two children stacked on top of each other in a trench coat',
    'Refuses to cover face while sneezing',
    "Won't stop juggling",
    'Has half a beard',
    'Absolutely refuses to shave',
    'Tells you to "suck it up" at a funeral',
    'Counts your calories',
    'Will only eat if you play airplane with their food',
    'Will only talk to you through Myspace',
    'Brings their own dishware to resturants',
    "50 Shades of Grey is the only book they've read",
    'Tells you to calm down after everything you say',
    'Has slept with everyone you work with',
    'Writes erotic Lassie fan fiction',
    'Has nineteen kids and counting',
    'Has plexiglass cheeks so that you can see inside their mouth',
    'Only talks like yoda',
    "Can only eat out of someone else's hand",
    'Sleep-puncher',
    'Puts "air quotes" around "every word" they say',
    'Keeps talking about someone who "looks just like you, only better!"',
    'Keeps asking if your best friend is "down"',
    'Posts all of your texts and messages online',
    'Super clingy',
    'Incapable of all emotion',
    'Always bragging about past sexual conquests',
    'Lives in a bedroom with eight dudes, including one named "Jug"',
    'Only speaks in business buzzwords',
    'Calls their pets their children',
    'Only eats deep-fried food',
    'Only talks about themselves',
    "Won't stop talking about their mother",
    "The two halves of their face don't match. Both are attractive but look totally different",
    'Talks dirty to all of their food',
    'Has a knee fetish',
    'Is always naked',
    "Doesn't know the difference between your and you're",
    'Is a hobbit',
    'Only responds to "Dr. Naughty"',
    'Thinks Twilight deserved an Oscar',
    'Starts every sentence with "actually"',
    'Amateur cannibal',
    'Has a permanent fedora',
    'Is always covered in ants',
    'Yells "ear muffs!" whenever they hear a bad word',
    'Sleeps in the downward dog position',
    'Is allergic to all of your favorite foods',
    "Thinks they're smarter than you",
    'Dabbles in torture',
    'Always wearing a Bluetooth headset',
    'Always wears a luchador mask',
    'Keeps changing the subject to talk about how not racist they are',
    'Is a 60 year old virgin',
    'Sells home-made pubic hair wigs',
    'As long as you date them you can only eat food off the dollar menu',
    'Uses the word "chillax" in every sentence',
    'Really stupid',
    'Only laughs at their own jokes',
    'Smells like a corpse',
    'Is "legally" married to their couch',
    "Can't make decisions",
    'Spends every date using dating apps',
    'Body type: Dumpster',
    'Owes the government one million dollars',
    'Really really hates children',
    'Collects human skulls, says they are "practically free!"',
    'Wears diapers for "convenience"',
    'Sold your pets on Craigslist',
    'Tinders during sex',
    "Thinks you're ugly",
    'Death row inmate',
    'Only wears clothing made of human hair',
    'Rigged to a time bomb',
    "Just got out of prison...but won't tell you what they were in for",
    'Refuses to look up from phone',
    'Compulsively licks windows',
    'Has never spelled a word corectly',
    'Name drops during dirty talk',
    'Refuses to wash hands',
    'Throws up every time they see your face',
    'In a band called "Genocide Warts"',
    'Immediately tries to kill you with a fork',
    'Backseat driver',
    'Eats crayons',
    'Compulsive liar',
    'Always dresses like a clown',
    'Only communicates with you via fax',
    'Hair is transplanted from cadaver butts',
    'Steals locks of your hair',
    'Constantly plotting to kill you',
    'Zero percent sexually attractive to you',
    'Farts every time they kiss you',
    'Is related to you',
    'Greets people by sniffing their butts',
    'Greets you with a headbutt',
    "Can't keep a job longer than twenty minutes",
    'Is a train wreck',
    'Only speaks in sarcasm',
    'Takes you to the post office on the first date',
    'Live-tweets your entire date',
    'Their pet name for you is "dishwasher"',
    'Brings mom to first date',
    'Yawns every time you start a sentence',
    'Static shocks you every time you touch',
    'Is addicted to prescription drugs',
    'Is six years old',
    "Doesn't understand your jokes",
    '3-foot fingernails',
    'Is building an ark',
    'Brings ex to first date',
    'Melts if they get wet',
    'Never stops talking',
    'Is a serial killer',
    'Reads over your shoulder (out loud)',
    "Doesn't believe in oral sex",
    'First name is "Dooker"',
    "Isn't toilet trained",
    'Describes all food as "yummy yummers"',
    'Open mouth kisses their siblings',
    'College nickname: Puke Crotch',
    "Is the person you hated the most in high school...and hasn't changed",
    'Is a zombie',
    'Only speaks in boy band lyrics',
    'Adds you as an emergency contact on the first date',
    'Always picking their nose',
    'Has been stalking you since middle school',
    "Doesn't like music...any of it",
    'Kicks every animal they see',
    'Burps and blows in your face',
    'For as long as you date them all your friends will hate you',
    'Takes you to couples therapy on the first date',
    'Has scissor hands',
    "Has a superpower. It's seeing through people's clothes",
    'Constantly trying to bang your friends',
    'Is on every fad diet at the same time',
    'Physically incapable of asking a question',
    "Knocks things out of strangers' hands while walking down the street",
    'Is the oldest living person',
    'Snorts powdered sugar. Really wants you to try it',
    'Still uses a flip phone',
    'Winks after every sentence',
    'Refuses to delete online dating profile',
    'Wears a backpack full of pudding during sex',
    'Swears you look exactly like their sister',
    'Never stops playing the ukelele',
    'Slept with one of your parents. Recently.',
    'Has two other spouses',
    'Hits on every server',
    'Is addicted to crack',
    'Uses cockpuppets',
    'Constantly hosts tea parties for dolls',
    'Can only have conversations through puppets',
    'Constantly freestyle raps...badly',
    "Calls you by ex's name...Every time",
    'Is a revenge porn mogul',
    'Only responds to texts with "k"',
    'Refers to their genitals as their "no-no"',
    'Lives off the grid',
    'Literally always on a Segway',
    'Jealous of your pet',
    'Texts exclusively in emojis',
    'Charges you 50c every time you say a curse word',
    'Open mouth kisses their pets',
    'Constantly taking selfies',
    'Every time you think about them you dry heave',
    'Afraid of sunlight',
    'Their sex tape with Jonah Hill just went viral',
    'Resting dumb face',
    'Ends every conversation with "I must go! My people need me!"',
    'Is on the no-fly list',
    'Recites all the lines from "Titanic" in their sleep',
    'Narrates everything they do outloud',
    'Is a vampire...not the sexy kind',
    'Keeps talking about their "hot cousin"',
    'Sexist',
    "Doesn't think women should vote",
    'Has toes for fingers',
    'Always takes the joke three steps too far',
    'Is afraid of stoplights',
    "Thinks they're a Jedi",
    'Has to pee every thirty minutes for five minutes',
    'Speaks with a constantly changing foreign accent',
    'Super super racist',
    'Only has sex standing up',
    'Only speaks Klingon',
    'Calls you their "Side Hustle"',
    'Screams while peeing',
    'Basic',
    'Can only speak in lines from The Emoji Movie'
]